apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: test-cicd-argo
build:
  artifacts:
    - image: piomin/test-cicd-argo
      jib:
        args:
          - -Pjib
          - -DskipTests
manifests:
  rawYaml:
    - k8s/deployment.yaml
deploy:
  kubectl: {}